CREATE TABLE
    public.chat_providers (
        id int8 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
        "name" text NOT NULL,
        CONSTRAINT chat_providers_pkey PRIMARY KEY (id)
    );

ALTER TABLE public.chat_providers ENABLE ROW LEVEL SECURITY;

CREATE POLICY authAll ON public.chat_providers AS PERMISSIVE FOR ALL TO authenticated USING (true);
