AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a WAFv2 Web ACL with managed rule sets.

Parameters:
  WafName:
    Type: String
    Description: The name of the WAFv2 Web ACL.
    Default: f2-core-waf

Resources:
  # =================================================================
  # 1. WAF WebACL
  # =================================================================
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref WafName
      Scope: REGIONAL # Or CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Ref WafName
        SampledRequestsEnabled: true
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 10
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: true
        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesAmazonIpReputationList
            SampledRequestsEnabled: true
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 30
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesKnownBadInputsRuleSet
            SampledRequestsEnabled: true

  # =================================================================
  # 2. Outputs
  # =================================================================
Outputs:
  WebACLArn:
    Description: The ARN of the WAFv2 Web ACL
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub "${AWS::StackName}-WebACLArn"
